### ISSUE TITLE
Different indexes in sqlserver not correctly created

### ISSUE THREAD

**Issue by calumsult** [sumeetchhetri/sqldiffer#1]
This is a cool project!

One thing I noticed is that in SQL Server if an index is missing it's not correctly creating it, it just does for example:

CREATE INDEX IX_Sample_Index_Name;

instead of correctly creating the index.

**Comment by sumeetchhetri** [comment]
Resolved with https://github.com/sumeetchhetri/sqldiffer/commit/df61062bd50670942661b5c2678e63e9652647e9
