### ISSUE TITLE
Install issue - no required module

### ISSUE THREAD

**Issue by gamesbook** [sumeetchhetri/sqldiffer#2]
When trying to install, I get this error:
```
common/common.go:12:2: no required module provides package github.com/sumeetchhetri/sqldiffer/protos; to add it:
	go get github.com/sumeetchhetri/sqldiffer/protos
```

Running `go get github.com/sumeetchhetri/sqldiffer/protos` gives error:
```
go: github.com/sumeetchhetri/sqldiffer/protos: no matching versions for query "upgrade"
```

Running `go version go1.18.1 linux/amd64` on Linux Mint 21.2 ( kernel is `5.15.0-92-generic` )

**Comment by sumeetchhetri** [comment]
Apologies for the super delayed response, this has been resolved.
